spring:
  application:
    name: location-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/test
    username: test
    password: test

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
  packages-to-scan: com.myproject.locationservice

server:
  port: 8086

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"

service:
  url: http://localhost:${server.port}